---
output: pdf_document
---

```{r, echo=FALSE, message=FALSE}
library(MSwM2)
library(ggplot2)
library(reshape2)

attach("C:/Users/EARAEAM/Dropbox/Thesis/Data/results_switch.Rdata")
```

```{r, echo=FALSE}
predictor2 <- c("RrcConnectionSetupComplete","Paging","X2HandoverRequest","Fdd.Tdd","NumCells")
fmla2 <- as.formula(paste("TotCpu ~ ", paste(predictor2, collapse= "+")))

mod_L16A <- lm(fmla2, data=train_g2_L16A)

#----------------------------------------------------------------#
# 5 = Fdd/Tdd
# 6-7 = NumCells

# (1) NN
switch <- rep(TRUE,length(mod_L16A$coefficients)+1+1)
names(switch) <- c(names(mod_L16A$coefficients),"AR","var")
switch[c(5,6,7)] <- FALSE 
set.seed(1)
mswm_L16A_NN <- MSwM2::msmFit(mod_L16A, k=3, p=1, sw=switch, control=list(trace=FALSE, maxiter=500, parallel=FALSE))
```

```{r, echo=FALSE, fig.width=14, fig.height=3}
#--------------------------------#
# smoothed prob plot
L16A_3 <- as.data.frame(mswm_L16A_NN@Fit@smoProb)
L16A_3 <- cbind(index=seq(1,nrow(L16A_3)),L16A_3)
colnames(L16A_3) <- c("index","State 1","State 2","State 3")

L16A_3 <- melt(L16A_3, id="index")
ggplot(data=L16A_3, aes(x=index, y=value, colour=variable)) + geom_line() +
    ylab("Smoothed Probabilities") + ggtitle("L16A_NN") + scale_color_manual(values=c("#F8766D","#00BA38","#619CFF")) +
    theme_bw() + theme(legend.title = element_blank())
```

```{r, echo=FALSE, fig.width=14, fig.height=3}
#--------------------------------#
# plot with state area
state_L16A_3 <- gen(mswm_L16A_NN, train_g2_L16A)
ggplot(data=state_L16A_3, aes(x=index, y=y)) + geom_line() +
    geom_rect(data=state_L16A_3, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=state), alpha=0.2, inherit.aes=FALSE) +
    scale_fill_manual(values=c("red","green","blue")) + 
    ylab("TotCpu") + ggtitle("L16A_NN") + theme_bw()
```


```{r, echo=FALSE}
# one test case per SW
predictor <- c("RrcConnectionSetupComplete","Paging","X2HandoverRequest","DuProdName","Fdd.Tdd","NumCells")
fmla <- as.formula(paste("TotCpu ~ ", paste(predictor, collapse= "+")))

mod_L16B <- lm(fmla, data=train_g2_L16B)

# plot with state area
gen <- function(object,data){
    state <- sapply(1:nrow(data), function(x) which.max(object@Fit@smoProb[x,]))
    state <- factor(state)
    index=seq(1,nrow(data))
    xmin=index-0.5
    xmax=index+0.5
    y=data$TotCpu
    ans <- data.frame(index,xmin,xmax,state,y=y,ymin=min(y),ymax=max(y))
    return(ans)
}

# (4) NYY
switch <- rep(TRUE,length(mod_L16B$coefficients)+1+1)
names(switch) <- c(names(mod_L16B$coefficients),"AR","var")
switch[c(5)] <- FALSE 
set.seed(1)
mswm_L16B_NYY <- MSwM2::msmFit(mod_L16B, k=3, p=1, sw=switch, control=list(trace=FALSE, maxiter=1000, parallel=FALSE))
```

```{r, echo=FALSE, fig.width=14, fig.height=3}
#--------------------------------#
# smoothed prob plot
L16B_3 <- as.data.frame(mswm_L16B_NYY@Fit@smoProb)
L16B_3 <- cbind(index=seq(1,nrow(L16B_3)),L16B_3)
colnames(L16B_3) <- c("index","State 1","State 2","State 3")

L16B_3 <- melt(L16B_3, id="index")
ggplot(data=L16B_3, aes(x=index, y=value, colour=variable)) + geom_line() +
    ylab("Smoothed Probabilities") + ggtitle("L16B_NYY") + scale_color_manual(values=c("#F8766D","#00BA38","#619CFF")) +
    theme_bw() + theme(legend.title = element_blank())
```

```{r, echo=FALSE, fig.width=14, fig.height=3}
#--------------------------------#
# plot with state area
state_L16B_3 <- gen(mswm_L16B_NYY, train_g2_L16B)
ggplot(data=state_L16B_3, aes(x=index, y=y)) + geom_line() +
    geom_rect(data=state_L16B_3, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=state), alpha=0.2, inherit.aes=FALSE) +
    scale_fill_manual(values=c("red","green","blue")) + 
    ylab("TotCpu") + ggtitle("L16B_NYY") + theme_bw()

```


```{r, echo=FALSE}
mod_L17A <- lm(fmla, data=train_g2_L17A)

#----------------------------------------------------------------#
# 5 = DuProdName
# 6 = Fdd/Tdd
# 7-9 = NumCells

# (1) NNN
switch <- rep(TRUE,length(mod_L17A$coefficients)+1+1)
names(switch) <- c(names(mod_L17A$coefficients),"AR","var")
switch[c(5,6,7,8,9)] <- FALSE 
set.seed(1)
mswm_L17A_NNN <- MSwM2::msmFit(mod_L17A, k=3, p=1, sw=switch, control=list(trace=FALSE, maxiter=500, parallel=FALSE))
```

```{r, echo=FALSE, fig.width=14, fig.height=3}
#--------------------------------#
# smoothed prob plot
L17A_3 <- as.data.frame(mswm_L17A_NNN@Fit@smoProb)
L17A_3 <- cbind(index=seq(1,nrow(L17A_3)),L17A_3)
colnames(L17A_3) <- c("index","State 1","State 2","State 3")

L17A_3 <- melt(L17A_3, id="index")
ggplot(data=L17A_3, aes(x=index, y=value, colour=variable)) + geom_line() +
    ylab("Smoothed Probabilities") + ggtitle("L17A_NNN") + scale_color_manual(values=c("#F8766D","#00BA38","#619CFF")) +
    theme_bw() + theme(legend.title = element_blank())
```


```{r, echo=FALSE, fig.width=14, fig.height=3}
#--------------------------------#
# plot with state area
state_L17A_3 <- gen(mswm_L17A_NNN, train_g2_L17A)
ggplot(data=state_L17A_3, aes(x=index, y=y)) + geom_line() +
    geom_rect(data=state_L17A_3, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=state), alpha=0.2, inherit.aes=FALSE) +
    scale_fill_manual(values=c("red","green","blue")) + 
    ylab("TotCpu") + ggtitle("L17A_NNN") + theme_bw()

```


